<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Introductory Programming in Python: Understanding Python's Error Messages</title>
	<link rel='stylesheet' type='text/css' href='style.css' />
	<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
	<script src="animation.js" type="text/javascript">
	</script>
</head>

<body onload="animate_loop()">
	<div class="page">

		<h1>Introductory Programming in Python: Lesson 24<br />

		Understanding Python's Error Messages</h1>

		<div class="centered">
			[<a href="writing_errors.html">Prev: Writing Meaningful Error Messages</a>]&nbsp;[<a href="index.html">Course Outline</a>]&nbsp;[<a href="exceptions.html">Next: Flow Control: Exceptions</a>]
		</div>

		<h2>Traceback most recent WHAT???</h2>

		<p>We are by now all familiar with the dreaded <code>Traceback (most
		recent call last):</code>. The sign that something has gone wrong, that
		your late night just got later, your assignment is rapidly becoming
		overdue, and that there's not nearly enough coffee left in the jug!
		Well, believe it or not, the messages Python prints are there to help
		you, as long as you are willing to read and understand them.</p>

		<h2>The Call Stack</h2>

		<p>First we need to understand the concept of the <em>call stack</em>. When we
		are running our Python program, the execution point moves around, from
		top to bottom, branching at if statements, looping with while or for
		statements, or jumping inside functions...  but this causes issues. If
		an error occurs in our main program block, it is easy to find the problem by 
                looking at the line on which the error occurred. There is generally only one way for
		execution to reach that line. But in a function, which can be called
		from many places within our program, including itself or other
		functions, knowing that the error occurred on a line in a particular
		function definition doesn't help us understand how the flow of
		execution led up to the error.</p>

                <p>Enter the <em>call stack</em>! Every time a
		function is called, Python pushes it on to something called the <em>call
		stack</em>. Think of a stack like getting into the elevator in a crowded
		mall. You get in first, and as more people enter the elevator, you are
		forced to the back. When you arrive at your floor, the last person in,
		now being closest to the door, exits first. If you want to get out in
		the middle somewhere, everyone who got in after you must briefly step
		out, to let you out, then go back in. This is exactly what happens with
		the <em>call stack</em>. As functions are called, their names are placed on the
		stack, and as they finish, their names are removed.</p>

                <p>The <em>traceback</em> presents us with the list of called function, from the first called to
		the most recent called (<code>most recent call last</code>). It gives us the following information:
                <ul>
                    <li>the file where the call occurred,</li>
                    <li>the line in that file,</li>
                    <li>the name of the function the call was made from (or '?' if it isn't a function), and</li>
                    <li>the line where the next function was called, or where the error occurred.</li>
                </ul>
                So let's go through the following traceback:</p>

		<pre class='listing'>
Traceback (most recent call last):
  File "test.py", line 25, in ?
    triangle()
  File "test.py", line 12, in triangle
    inc_total_height()
  File "test.py", line 8, in inc_total_height
    total_height = total_height + height
UnboundLocalError: local variable 'total_height' referenced before assignment
</pre>

		<p>We see that execution started in the file test.py and proceeded to
		line 25, where the function 'triangle' was called. Within the function
		triangle, execution proceeded until line 12, where the function
		'inc_total_height' was called. Within 'inc_total_height' and error
		occurred on line 8.</p>

		<h2>So what went wrong?</h2>

		<p>The last line, or sometimes two lines, of the traceback describe
		what actually went wrong. In Python, all errors are given a class, e.g.
		input/output error, undefined variable or index out of range.
		These classes are given names that are one word without spaces. 
                The class name of the error describes roughly what type of
		error occurred and it is printed first. Then everything following the
		colon (':') is further description of the actual variables,
		expressions, and statements involved in the error, and what they were
		doing. So we can tell from the above example that the class was
		'UnboundLocalError' and that the local variable 'total_height' was
		referenced, or evaluated, before a value was assigned to it.</p>

		<p>Learning the meaning of the class names comes with time, but the
		description following is usually sufficient to point you in the right
		direction. At least now you can track down exactly what line is causing
		the problem, and how the program got there.</p>
                
                <h2>Error types</h2>

                <p>As mentioned before, Python errors are divided into classes - lots of them!
                Luckily only a handful are very common. These are listed here, in alphabetical order,
                so that you can figure out what you did wrong when you encounter one of these errors. Remember that
                there are various things that cause these errors. Only the most common reasons are mentioned here. Copy and paste the error message
                right into a Google search and you are sure to find an answer. And don't worry - 
                everyone, even experienced software engineers, run into these on a regular basis.</p>
                
                <h3>IndentationError</h3>
                <h4>Example:</h4>
                <pre class="listing">
for i in range(0, 10):
...     b = i
...   print i
  File "<stdin>", line 3
    print i
          ^
IndentationError: unindent does not match any outer indentation level</pre>
                
                <p>IndentationError is actually a special type of SyntaxError. You get this error when your indentation is not consistent. In the 
                example <code>b = i</code> has 4 leading spaces but <code>print i</code> only has 2. If <code>print i</code> needs to be executed
                for every iteration of the 'for' loop, then it needs to have the same level of indentation as the inner block, i.e. the same as <code>b = i</code>.
                Otherwise, if it is only meant to execute after the 'for' loop, it needs to have 0 leading spaces.</p>

                <h3>NameError</h3>
                <h4>Example:</h4>
                <pre class="listing">
print(variable)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'variable' is not defined</pre>
                
                <p>A 'NameError' occurs when you try to use a variable which does not exist in the current <em>scope</em>. In other words
                it has not been defined in the scope you are trying to use it in. Perhaps you haven't defined it at all, or
                perhaps you misspelt the variable name.</p>

                <h3>IndexError</h3>
                <h4>Example:</h4>
                <pre class="listing">
i = ['hello', 'world']
i[2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range</pre>
                
                <p>This error is an easy one to understand. In the example the list 'i' only has 2 elements. Those elements
                have index 0 and 1 (or -2 and -1 if you use reverse indices). Thus index 2 is 'out of range' because it is too large.
                IndexError will happen for any index that is too large or too small.</p>

                <h3>SyntaxError</h3>
                <h4>Example:</h4>
                <pre class="listing">
print('hello world!)
  File "<stdin>", line 1
    print('hello world!)
                       ^
SyntaxError: EOL while scanning string literal</pre>
                <pre class="listing">
answer = ((1 + 3) * 5 / 6.0 ;
  File "<stdin>", line 1
    answer = ((1 + 3) * 5 / 6.0 ;
                                ^
SyntaxError: invalid syntax</pre>
                <p>Syntax errors occur when Python cannot understand your code because you didn't use the correct 'grammar'. While you can
                get away with the occasional grammar mistake in English, the same cannot be said of computer languages. Things have to be
                exactly right. Luckily syntax errors are easy to solve if you understand the error message. The '^' character in the error message
                points to the place where Python encountered the error. In the
                first example above, a closing single quote is missing. In the second example it is a closing bracket that is missing.
                Always check that you having matching closing and opening brackets and quotes.</p>
                
                <h4>Example:</h4>
                <pre class="listing">
File "Desktop/errors.py", line 1
    for i in range(0, 10)
                        ^
SyntaxError: invalid syntax</pre>

                <p>Another common syntax error is leaving out the colon (':') at the start of a code block. 'if', 'for' and 'while' statements, as well as function
                definitions, all start new code blocks. So those lines have to end with a colon.</p>
                <h3>TypeError</h3>
                <h4>Example:</h4>
                <pre class="listing">
'ab' * 'ab'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't multiply sequence by non-int of type 'str'</pre>
                <pre class="listing">
def multiply(a, b):
    return a * b

multiply(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: multiply() takes exactly 2 arguments (1 given)</pre>
                
                <p>When you use the wrong type of variable for something in Python, you will get a TypeError. In the first example, Python
                cannot multiply two variables that are strings. At least one of them needs to be a number. The second example is an altogether
                different TypeError. The function <code>def multiply(a, b)</code> needs two arguments to be passed to it, e.g. <code>multiply(10, 15)</code>.
                Too many or too few arguments will also cause a TypeError.</p>

                <h3>ValueError</h3>
                <h4>Example:</h4>
                
                <pre class="listing">
int('abc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'abc'</pre>
                
                <p>Value errors can occur for many different reasons. It means that there is something 'wrong' about the value of a variable or 
                literal. In the example above the value in question is 'abc' and the program is trying to turn 'abc' into an integer. How does one
                turn 'abc' into a number? I don't know and neither does Python. That is why a ValueError pops up.</p>
                
                <p><strong>Remember, if you cannot find an answer here, just copy-paste the error message into Google!</strong></p>
		<div class="centered">
			[<a href="writing_errors.html">Prev: Writing Meaningful Error Messages</a>]&nbsp;[<a href="index.html">Course Outline</a>]&nbsp;[<a href="exceptions.html">Next: Flow Control: Exceptions</a>]
		</div>
	</div>

	<div class="pagefooter">
		Copyright &copy; James Dominy 2007-2008; Released under the <a href="http://www.gnu.org/copyleft/fdl.html">GNU Free Documentation License</a><br />
		<a href="intropython.tar.gz">Download the tarball</a>
	</div>
</body>
</html>
